### ISSUE TITLE
2주차에 할 것

### ISSUE THREAD

**Issue by l2hyunwoo** [BE-SOPT-Android-First-Class/HyunWooRoid#9]
- [ ] 다크모드 설정
- [ ] DataStore에 Encryption/Decryption 적용하기
- [ ] EncryptedFile/EncryptedSharedPreference 활용해서 MockServer 만들기
- [ ] 로그인 화면 애니메이션 설정
- [ ] 지문인식 로그인 만들어보기
- [ ] 리사이클러뷰 만들어보기

**Comment by mdb1217** [comment]
저번 기수도 생각했지만 진짜 지문인식에 진심이시네요. 질 수 없다! 카메라x 바로 가..!
